def PARTIDA_GASTO(data):
    # Generamos la variable PARTIDA_GASTO
    data['PARTIDA_GASTO'] = ""
    # GG1
    data.loc[(data['GENERICA'].str.contains("PERSONAL Y OBLIGACIONES SOCIALES")) & (data['SUBGENERICA_DET'] != "13. CONTRATO ADMINISTRATIVO DE SERVICIOS")  & (data['SUBGENERICA_DET'] != "1. PAGO DE SENTENCIAS JUDICIALES EN CALIDAD DE COSA JUZGADA POR ADEUDOS"), 'PARTIDA_GASTO'] = "2.1. PERSONAL Y OBLIGACIONES SOCIALES"
    data.loc[data['SUBGENERICA_DET'].str.contains("CONTRATO ADMINISTRATIVO DE SERVICIOS"), 'PARTIDA_GASTO'] = "2.1.1.13.1. CONTRATO ADMINISTRATIVO DE SERVICIOS"
    data.loc[data['SUBGENERICA_DET'].str.contains("PAGO DE SENTENCIAS JUDICIALES EN CALIDAD DE COSA JUZGADA POR ADEUDOS"), 'PARTIDA_GASTO'] = "2.1.5.1.1. PAGO DE SENTENCIAS JUDICIALES EN CALIDAD DE COSA JUZGADA POR ADEUDOS"
    # GG2
    data.loc[data['GENERICA'].str.contains("PENSIONES Y OTRAS PRESTACIONES SOCIALES") & data['SUBGENERICA_DET'].str.contains("PENSIONES"), 'PARTIDA_GASTO'] = "2.2. PENSIONES Y OTRAS PRESTACIONES SOCIALES"
    data.loc[data['GENERICA'].str.contains("PENSIONES Y OTRAS PRESTACIONES SOCIALES") & data['SUBGENERICA_DET'].str.contains("PRESTACIONES DE SALUD Y OTROS BENEFICIOS"), 'PARTIDA_GASTO'] = "2.2. PENSIONES Y OTRAS PRESTACIONES SOCIALES"
    data.loc[data['GENERICA'].str.contains("PENSIONES Y OTRAS PRESTACIONES SOCIALES") & data['SUBGENERICA_DET'].str.contains("ASISTENCIA SOCIAL EN PENSIONES E INDEMNIZACIONES"), 'PARTIDA_GASTO'] = "2.2. PENSIONES Y OTRAS PRESTACIONES SOCIALES"
    data.loc[data['SUBGENERICA_DET'].str.contains("PENSIONES") & data['SUBGENERICA_DET'].str.contains("PAGO DE SENTENCIAS JUDICIALES EN CALIDAD DE COSA JUZGADA Y LAUDOS ARBITRALES DEFINITIVOS POR ADEUDOS"), 'PARTIDA_GASTO'] = "2.2.1.2.1. PAGO DE SENTENCIAS JUDICIALES EN CALIDAD DE COSA JUZGADA POR ADEUDOS"
    data.loc[data['GENERICA'].str.contains("PENSIONES Y OTRAS PRESTACIONES SOCIALES") & data['SUBGENERICA_DET'].str.contains("ENTREGA DE BIENES Y SERVICIOS") & data['ESPECIFICA'].str.contains("OTRAS PRESTACIONES DEL EMPLEADOR"), 'PARTIDA_GASTO'] = "2.2. PENSIONES Y OTRAS PRESTACIONES SOCIALES"
    # GG3
    data.loc[data['CLASIFICADOR_GASTO'].str.contains("5.2.3.2.7.5"), 'PARTIDA_GASTO'] = "2.3.2.7.5. PRACTICANTES, SECIGRISTAS Y SIMILARES"
    data.loc[(data['ESPECIFICA_DET'].str.contains("FONDO DE APOYO GERENCIAL")) | (data['ESPECIFICA_DET'].str.contains("PERSONAL ALTAMENTE CALIFICADO")), 'PARTIDA_GASTO'] = "2.3.2.7.12. OTRAS MODALIDADES DE CONTRATACION DE PERSONAS NATURALES"
    data.loc[data['CLASIFICADOR_GASTO'] == "5.2.3.2.9.1.1", 'PARTIDA_GASTO'] = "2.3.2.9.1.1. LOCACIÓN DE SERVICIOS RELACIONADAS AL ROL DE LA ENTIDAD"
    # GG4 y GG5 SENTENCIAS JUDICIALES
    data.loc[data['SUBGENERICA_DET'].str.contains("PAGO DE SENTENCIAS JUDICIALES Y LAUDOS ARBITRALES"), 'PARTIDA_GASTO'] = "2.5.5.1. PAGOS DE SENTENCIAS/LAUDOS"
    data.loc[data['SUBGENERICA_DET'].str.contains("INDEMNIZACIONES Y COMPENSACIONES"), 'PARTIDA_GASTO'] = "2.5.5.2. INDEMNIZACIÓN/COMPENSACIÓN"
    data.loc[((data['PLIEGO'].str.contains("M. DEL INTERIOR")) | (data['PLIEGO'].str.contains("M. DE DEFENSA"))) & (data['FUNCION'].str.contains("24")) & (data['ESPECIFICA_DET'].str.contains("A OTRAS ORGANIZACIONES")), 'PARTIDA_GASTO'] = "2.5.2. TRANSFERENCIAS A LA CAJA DE PENSIONES MILITAR POLICIAL"
    #GG5 NEGOCIACIONES COLECTIVA
    data.loc[data['CLASIFICADOR_GASTO'] == "5.2.5.6.1.1.1", 'PARTIDA_GASTO'] = "2.5.6.1.1.1. NEGOCIACIÓN COLECTIVA - NIVEL DESCENTRALIZADO POR ENTIDAD PÚBLICA"
    data.loc[data['CLASIFICADOR_GASTO'] == "5.2.5.6.1.1.2", 'PARTIDA_GASTO'] = "2.5.6.1.1.2. NEGOCIACIÓN COLECTIVA - NIVEL DESCENTRALIZADO EN EL ÁMBITO SECTORIAL"
    return data